name: sdpify
description: "Sdpify - Scalable Density Pixels for Responsive UI"
version: 1.0.1

repository: https://github.com/shariarunix/Sdpify
homepage: https://github.com/shariarunix/Sdpify
issue_tracker: https://github.com/shariarunix/Sdpify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
