name: sdpify
description: "Sdpify is a lightweight package that provides Scalable Density Pixels (SDP) to ensure a consistent UI across different screen sizes and densities. It dynamically converts pixel-based values (px) into scalable dp (sdp), making your app adaptive and responsive on all devices."
version: 1.0.1

repository: https://github.com/shariarunix/Sdpify
homepage: https://github.com/shariarunix/Sdpify
issue_tracker: https://github.com/shariarunix/Sdpify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
