name: sdpify
description: "Sdpify is a lightweight package that converts pixels to scalable dp (sdp), ensuring a responsive and consistent UI across all screen sizes and densities"
version: 1.0.3

repository: https://github.com/shariarunix/Sdpify
homepage: https://github.com/shariarunix/Sdpify
issue_tracker: https://github.com/shariarunix/Sdpify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
